trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'SQL-Test/Test_SQL.py'
    arguments: '''mysqladmin@databasedevops9292'' $(SQL_PASSWORD) ''databasedevops9292.mysql.database.azure.com'' ''cloudskills'''
