name: Build and Deploy MySQL for Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working_directory: SQL-Server-Creation
      CLIENT_ID: 1073055c-2228-416f-8abd-fefd8ea55593
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      SUBSCRIPTION_ID: 220284d2-6a19-4781-87f8-5c564ec4fec9
      TENANT_ID: fbbd9689-2869-42b8-92fb-db1c89b662ff

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_token: ${{ secrets.CLIENT_SECRET }}
      
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ env.working_directory }}
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -var="password=${{ secrets.SQL_PASSWORD }}" -var="ip_address=$${{ secrets.IP_ADDRESS }}"
      working-directory: ${{ env.working_directory }}

